/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnagraficaRouteImport } from './routes/anagrafica'
import { Route as CertificazioniRouteImport } from './routes/certificazioni'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EserciziRouteImport } from './routes/esercizi'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ProgressiRouteImport } from './routes/progressi'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ScuolaRouteImport } from './routes/scuola'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsCodeRouteImport } from './routes/sessions.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnagraficaRoute = AnagraficaRouteImport.update({
  id: '/anagrafica',
  path: '/anagrafica',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificazioniRoute = CertificazioniRouteImport.update({
  id: '/certificazioni',
  path: '/certificazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EserciziRoute = EserciziRouteImport.update({
  id: '/esercizi',
  path: '/esercizi',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressiRoute = ProgressiRouteImport.update({
  id: '/progressi',
  path: '/progressi',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ScuolaRoute = ScuolaRouteImport.update({
  id: '/scuola',
  path: '/scuola',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PlayersRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsCodeRoute = SessionsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anagrafica': typeof AnagraficaRoute
  '/certificazioni': typeof CertificazioniRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/esercizi': typeof EserciziRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/players': typeof PlayersRouteWithChildren
  '/progressi': typeof ProgressiRoute
  '/ranking': typeof RankingRoute
  '/rules': typeof RulesRoute
  '/scuola': typeof ScuolaRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/team': typeof TeamRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sessions/$code': typeof SessionsCodeRoute
  '/players/': typeof PlayersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anagrafica': typeof AnagraficaRoute
  '/certificazioni': typeof CertificazioniRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/esercizi': typeof EserciziRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/progressi': typeof ProgressiRoute
  '/ranking': typeof RankingRoute
  '/rules': typeof RulesRoute
  '/scuola': typeof ScuolaRoute
  '/team': typeof TeamRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sessions/$code': typeof SessionsCodeRoute
  '/players': typeof PlayersIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anagrafica': typeof AnagraficaRoute
  '/certificazioni': typeof CertificazioniRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/esercizi': typeof EserciziRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/players': typeof PlayersRouteWithChildren
  '/progressi': typeof ProgressiRoute
  '/ranking': typeof RankingRoute
  '/rules': typeof RulesRoute
  '/scuola': typeof ScuolaRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/team': typeof TeamRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sessions/$code': typeof SessionsCodeRoute
  '/players/': typeof PlayersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anagrafica'
    | '/certificazioni'
    | '/compare'
    | '/dashboard'
    | '/esercizi'
    | '/import'
    | '/insights'
    | '/players'
    | '/progressi'
    | '/ranking'
    | '/rules'
    | '/scuola'
    | '/sessions'
    | '/team'
    | '/players/$playerId'
    | '/sessions/$code'
    | '/players/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anagrafica'
    | '/certificazioni'
    | '/compare'
    | '/dashboard'
    | '/esercizi'
    | '/import'
    | '/insights'
    | '/progressi'
    | '/ranking'
    | '/rules'
    | '/scuola'
    | '/team'
    | '/players/$playerId'
    | '/sessions/$code'
    | '/players'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/anagrafica'
    | '/certificazioni'
    | '/compare'
    | '/dashboard'
    | '/esercizi'
    | '/import'
    | '/insights'
    | '/players'
    | '/progressi'
    | '/ranking'
    | '/rules'
    | '/scuola'
    | '/sessions'
    | '/team'
    | '/players/$playerId'
    | '/sessions/$code'
    | '/players/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnagraficaRoute: typeof AnagraficaRoute
  CertificazioniRoute: typeof CertificazioniRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  EserciziRoute: typeof EserciziRoute
  ImportRoute: typeof ImportRoute
  InsightsRoute: typeof InsightsRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  ProgressiRoute: typeof ProgressiRoute
  RankingRoute: typeof RankingRoute
  RulesRoute: typeof RulesRoute
  ScuolaRoute: typeof ScuolaRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anagrafica': {
      id: '/anagrafica'
      path: '/anagrafica'
      fullPath: '/anagrafica'
      preLoaderRoute: typeof AnagraficaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificazioni': {
      id: '/certificazioni'
      path: '/certificazioni'
      fullPath: '/certificazioni'
      preLoaderRoute: typeof CertificazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esercizi': {
      id: '/esercizi'
      path: '/esercizi'
      fullPath: '/esercizi'
      preLoaderRoute: typeof EserciziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressi': {
      id: '/progressi'
      path: '/progressi'
      fullPath: '/progressi'
      preLoaderRoute: typeof ProgressiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scuola': {
      id: '/scuola'
      path: '/scuola'
      fullPath: '/scuola'
      preLoaderRoute: typeof ScuolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$code': {
      id: '/sessions/$code'
      path: '/$code'
      fullPath: '/sessions/$code'
      preLoaderRoute: typeof SessionsCodeRouteImport
      parentRoute: typeof SessionsRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface SessionsRouteChildren {
  SessionsCodeRoute: typeof SessionsCodeRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsCodeRoute: SessionsCodeRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnagraficaRoute: AnagraficaRoute,
  CertificazioniRoute: CertificazioniRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  EserciziRoute: EserciziRoute,
  ImportRoute: ImportRoute,
  InsightsRoute: InsightsRoute,
  PlayersRoute: PlayersRouteWithChildren,
  ProgressiRoute: ProgressiRoute,
  RankingRoute: RankingRoute,
  RulesRoute: RulesRoute,
  ScuolaRoute: ScuolaRoute,
  SessionsRoute: SessionsRouteWithChildren,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
